### ISSUE TITLE
Task 4 Rules Userpoints Assignment

### ISSUE THREAD

**Issue by griffdogman** [griffdogman/First-Repo#3]
This task is to use Rules and to add userpoints to a registered user based on their $$Dollars spent on the site Rounded down to the nearest dollars after Tax, GST or any VAT Tax has been added.

[Task 4 userpoints assignment.pdf](https://github.com/griffdogman/First-Repo/files/233350/Task.4.userpoints.assignment.pdf)

**Comment by darshi-shah** [comment]
Hi Steve,

I went through the documentation you provided. Can you please explain about plans and what needs to be done ? 

I will be available on skype for chat.  

Thanks 
Darshi

**Comment by darshi-shah** [comment]
Hi Steve,

I have been working on this and I found multiple issues that I need to solve before we can implement this functionality. 

The major error I have is that on order complete, I get white screen.

Another error I can see from log file is functional redeclaration. 

`PHP Fatal error:  Cannot redeclare _mimemail_replace_files() (previously declared in /var/www/First-Repo/sites/all/modules/messaging/messaging_htmlmail/messaging_htmlmail.inc:422) in /var/www/First-Repo/sites/all/modules/mimemail/mimemail.inc on line 144, referer: http://localhost/First-Repo/ms/checkout/ms_userpoints`

Also, If I add user points manually, it gets additional 100points. Please explain how points are allocated and what are different types.


Thanks
Darshi

**Comment by griffdogman** [comment]
Hi Darshi,

On My server I have done the following:
1) I disabled mimemail and the Php Fatal  error has gone away ... I don't believe that module is required.

2) On my server I removed a rule that added 100 points, if you check on your system their is a rule which you can remove.

Regards

Steve

**Comment by griffdogman** [comment]
Darshi,

To fix these errors do you want me to do a Pull Push on the Development site .. If yes can you tell me what the git command is to update the development site ?

Regards

Steve
