### ISSUE TITLE
Code/git cleanup

### ISSUE THREAD

**Issue by darshi-shah** [griffdogman/First-Repo#5]
Hi Steve,

The existing code structure has some extra folders in it. We will be cleaning this first.

Currently, we have only one branch in this repository. We will create 2 more branches : develop and staging. Develop branch is where all active development is done. Staging branch will be exact replica of master branch and develop branch will be merged to this to test new features.

Also, you need to create a staging site and link it to this repository. Staging site will have staging branch. We will  use this site to deploy our changes and you can check the work on this before moving it to live site(master branch).

Let us know any questions regarding this.

Thanks

**Comment by griffdogman** [comment]
All good .. I just have to workout how to make a " staging site and link it to this repository"  I will try
Regards
Steve

**Comment by darshi-shah** [comment]
Hi,

I can see two branches in git repository but they are not added via git. I will add branches and then push them in git. I will let you know once done. 

Please leave this issue open till we have git organized. 


Thanks

**Comment by darshi-shah** [comment]
Hi Steve,

Extra files and folder are removed from git. These includes following : 

2ndhand 
home 
sxd 
the2ndhand
Backup files for index.html, index.php, testing file

The image folder is not removed. Let me know if this can be removed as well.
Thanks
Darshi

**Comment by griffdogman** [comment]
Thanks Darshi

I am currently using the image directory, I hope its o.k to stay.

Regards

Steve

**Comment by darshi-shah** [comment]
Hi Steve,

Thanks for informing. I will not remove this folder.

Thanks
Darshi
